# Generated by Django 3.0.4 on 2020-03-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
